name: project-env
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.11
  - pandas>=2
  - numpy
  - scipy
  - statsmodels
  - linearmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - missingno
  - pyjanitor
  - tqdm
  - jupyterlab
  - ipykernel
  - pytest
  - black
  - isort
  - flake8
  - openpyxl
  - xlrd
  - pathlib
  - pip
  - pip:
    - janitor
    - plotly
    - nbformat
    - tabulate
    - watermark
